export const DummyData = [
  {
    title: 'D To be or not to be that is the question',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Periodik',
    category: ['Revista Periodike Shkencore', 'Mesimor'],
    field: 'E drejta Penale',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image: 'https://edit.org/images/cat/book-covers-big-2019101610.jpg',
    file: '',
    userProgress: 20,
  },
  {
    title: 'C To be or not to be that is the question',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Periodik',
    category: ['Revista Periodike Profesionale', 'Mesimor'],
    field: 'E Drejta Civile',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image:
      'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/sad-romance-kindle-book-cover-flyer-template-539b5fdf2dd2f6602c25ce81fbb5d877_screen.jpg?ts=1636978269',
    file: '',
    userProgress: 100,
  },
  {
    title: 'B To be or not to be that is the question',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Periodik',
    category: ['Revista Periodike Shkencore', 'Mesimor'],
    field: 'E Drejta Penale',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image:
      'https://pub-static.fotor.com/assets/projects/pages/f9440db0-93f8-11e9-bd39-fddb51343e46_2531d93a-4d1f-4df1-897a-67cfb79f4b46_thumb.jpg',
    file: '',
    userProgress: 50,
  },
  {
    title: 'A To be or not to be that is the question',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Periodik',
    category: ['Revista Periodike Profesionale', 'Mesimor'],
    field: 'E Drejta Penale',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image: 'https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg',
    file: '',
    userProgress: 80,
  },
  {
    title:
      'This is a long title to test the text overflow property at two lines',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Liber',
    category: ['Manual', 'Mesimor'],
    field: 'E Drejta Penale',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image:
      'https://marketplace.canva.com/EAD7WuSVrt0/1/0/1003w/canva-colorful-illustration-young-adult-book-cover-LVthABb24ik.jpg',
    file: '',
    userProgress: 0,
  },
  {
    title: 'Short Title',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Liber',
    category: ['Monografi', 'Mesimor'],
    field: 'E drejta Penale',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image:
      'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/action-thriller-book-cover-design-template-3675ae3e3ac7ee095fc793ab61b812cc.jpg?ts=1637008457',
    file: '',
    userProgress: 100,
  },
  {
    title: 'B To be or not to be that is the question',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Liber',
    category: ['Cikel Leksionesh', 'Mesimor'],
    field: 'E Drejta Civile',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image: 'https://template.canva.com/EADaopxBna4/1/0/251w-ujD6UPGa9hw.jpg',
    file: '',
    userProgress: 80,
  },
  {
    title: 'A To be or not to be that is the question',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Liber',
    category: ['Tekst Mesimor', 'Mesimor'],
    field: 'E Drejta Penale',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image:
      'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/action-thriller-book-cover-design-template-3675ae3e3ac7ee095fc793ab61b812cc.jpg?ts=1637008457',
    file: '',
    userProgress: 50,
  },
  {
    title: 'D To be or not to be that is the question',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Liber',
    category: ['Komentar', 'Mesimor'],
    field: 'E Drejta Penale',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFzOM5LFSR3v6j2qX7GWhLn0jy7NkjBliSC1Ako3PfsoI_gV6B0-HEfzrB7C6_jmTrclM&usqp=CAU',
    file: '',
    userProgress: 10,
  },
  {
    title: 'D To be or not to be that is the question',
    author: ['John Doe', 'Joana Doe'],
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quia, odio?',
    type: 'Periodik',
    category: ['Revist Periodike Shkencore', 'Mesimor'],
    field: 'E Drejta Penale',
    isbn_code: '46858',
    publish_date: '22/22/2222',
    page_nr: '66',
    image:
      'https://i0.wp.com/www.casualoptimist.com/wp-content/uploads/2021/10/bewilderment-design-jennifer-griffiths.jpg?resize=1000%2C1500',
    file: '',
    userProgress: 0,
  },
];
